Settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="My API description",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="Awesome License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('', include('front.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    # path('ckeditor5/', include('django_ckeditor_5.urls')),
    # path('api/', include('api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

front/urls.py
from . import views
from django.urls import path

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('quiz-detail/<str:code>/', views.quiz_detail, name='quiz_detail'),
]

front/views.py
import xlsxwriter
from django.http import HttpResponse
from django.shortcuts import render, redirect
from main import models


def index(request):
    quizzes = models.Quiz.objects.all()
    context = {
        'quizzes':quizzes
    }
    return render(request, 'front/index.html', context)



def quiz_detail(request, code):
  quiz = models.Quiz.objects.get(code=code)
  questions = models.Question.objects.filter(quiz=quiz)
  if request.method == 'POST':
    answer = models.Answer.objects.create(
        quiz=quiz,
        user_name=request.POST['user_name'],
        phone=request.POST.get('phone'),
        email=request.POST.get('email')
    )
    for key, value in request.POST.items():
      if key.startswith('question'):
        question_id = int(key[len('question['):-len(']')])
       
        models.AnswerDetail.objects.create(
            answer=answer,
            question_id=question_id,
            user_answer_id=int(value)
        )
  context = {
    'quiz': quiz,
    'questions': questions
  }
  return render(request, 'front/quiz-detail.html', context)



def quiz_results_to_excel(quiz, answers, filename):
    workbook = xlsxwriter.Workbook(filename)
    worksheet = workbook.add_worksheet()

    headers = ['Ism Familiya', 'Telefon raqam', 'Email', 'Jami savollar', 'To`g`ri javoblar', 'Noto`g`ri javoblar']
    for col, header in enumerate(headers):
        worksheet.write(0, col, header)

    for row, answer in enumerate(answers, start=1):
        worksheet.write(row, 0, answer.user_name)
        worksheet.write(row, 1, answer.phone)
        worksheet.write(row, 2, answer.email)
        total_questions = answer.answerdetail_set.count()
        worksheet.write(row, 3, total_questions)
        correct_answers = answer.answerdetail_set.filter(user_answer__is_correct=True).count()
        worksheet.write(row, 4, correct_answers)
        incorrect_answers = total_questions - correct_answers
        worksheet.write(row, 5, incorrect_answers)

    workbook.close()

    return filename


def quiz_result(request, code):
    quiz = models.Quiz.objects.get(code=code)
    answers = models.Answer.objects.filter(quiz=quiz)

    filename = 'quiz_results.xlsx'
    excel_file = quiz_results_to_excel(quiz, answers, filename)

    with open(excel_file, 'rb') as f:
        response = HttpResponse(f.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response

templates/front/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin paneli</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.png' %}">

    <!-- page css -->
    <link href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- Core css -->
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Page Container START -->
            <div class="page-container">
                
                {% block content %}
                {% endblock %}
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0"> © 2024 Xudoyberdiyev Azizbek tomonidan qilingan sayt</p>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="{% static 'js/vendors.min.js' %}"></script>

    <!-- page js -->
    <script src="{% static 'vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/pages/dashboard-project.js' %}"></script>
    

    <!-- Core JS -->
    <script src="{% static 'js/app.min.js' %}"></script>

</body>

</html>

templates/front/index.html
{% extends 'front/base.html' %}

{% block content %}


<div class="main-content">
    
    <div style="margin-right: 200px;" class="card">
        <div class="card-body">
            <h4>Quizlar ro`yxati</h4>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Quiz nomi</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for quiz in quizzes %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td><a style="color: black" href="{% url 'front:quiz_detail' quiz.code %}"> <b> {{quiz.name}} </b></a> </td>
                                <td><button class="btn btn-rounded" onclick="myFunction('{% url 'front:quiz_detail' quiz.code %}')"><i class="text-primary anticon anticon-link"></i></button></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function myFunction(url) {
        var inp = document.createElement('input');
        document.body.appendChild(inp);
        inp.value = url.startsWith('/') ? '127.0.0.1:8000' + url : '127.0.0.1:8000/' + url;
        inp.select();
        document.execCommand('copy', false);
        inp.remove();
        alert('Savolning linki copy qilindi!');
    }
</script>



{% endblock %}

templates/front/quiz-detail.html
{% extends 'front/base.html' %}

{% block content %}
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Quiz</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Quizlar</a>
                <span class="breadcrumb-item active">{{ quiz.name }}</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <form id="quiz-form" action="" method="post">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="user_name">Full name</label>
                    <input type="text" class="form-control" id="user_name" placeholder="Full name" name="user_name" required>
                </div>
                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" placeholder="+998********" name="phone">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="example@gmail.com" name="email">
                </div>
                {% for question in questions %}
                <div class="container">
                    <div class="d-flex justify-content-between">
                    <h2 class="font-weight-normal m-b-10">{{ forloop.counter }}. {{ question.name | striptags }}</h2>
                    </div>
                    <div class="card-body">
                    <div class="m-t-25">
                        {% for option in question.options %}
                        <div class="radio">
                            <input id="radio{{ question.id }}_{{ option.id }}" 
                                name="question[{{ question.id }}]"  type="radio" value="{{ option.id }}">
                            <label for="radio{{ question.id }}_{{ option.id }}">{{ option.name }}</label>
                        </div>
                        {% endfor %}
                    </div>
                    </div>
                </div>
                {% endfor %}

            </div>
            <button class="btn btn-success" type="submit" data-toggle="modal" data-target="#resultModal">Yuborish</button>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="resultModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resultModalLabel">Result</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3 id="resultText">To'g'ri javoblar soni: {{ correct }}</h3>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/front/result.html
{% extends 'front/base.html' %}

{% block content %}
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Quiz Results</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Quiz Results</a>
                <span class="breadcrumb-item active">User Results</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h3>User Ma'lumotlari:</h3>
            <p><strong>Ism:</strong> {{ answers.user_name }}</p>
            <p><strong>Tel:</strong> {{ answers.phone }}</p>
            <p><strong>Email:</strong> {{ answers.email }}</p>
            <h3>Quiz Natijalari:</h3>
            <p><strong>Umumiy savollar:</strong> {{ total_quizzes }}</p>
            <p><strong>To'g'ri javoblar:</strong> {{ correct }}</p>
            <p><strong>Noto'g'ri javoblar:</strong> {{ incorrect }}</p>
        </div>
    </div>
</div>
{% endblock %}